### ISSUE TITLE
Increasing validation cost

### ISSUE THREAD

**Issue by TsainGra** [mleimeister/ctc_tensorflow_voxforge#1]
For the results that you got in your decoded_single_layer_blstm file, were they achieved with the same hyper-parameters? My validation cost starts increasing after a few epochs. Training cost is just fine.

Thanks.

**Comment by mleimeister** [comment]
Hi, 

the decodings that are displayed in decoded_single_layer_blstm.txt are from the first batch of the training data, and the LER reported is also the training error. This was basically meant to explore which kind of errors the algorithm does on the training set and how they improve during training. For the validation set, the error kept oscillating for me around 0.7-0.8. Given the little training data I used this is kind of expected I'd say. For me the project was just a trial how to use the ctc_loss rather than build a functional model. One way to go would be to download much more data from voxforge and do an exhaustive hyperparameter search. Let me know if you have any more questions.

Best regards,
Matthias

**Comment by TsainGra** [comment]
To add more data, if I just append the wav_files as
 `    wav_files.append(list_files_for_speaker('<name>', voxforge_data_dir))`
will it work?
P.S. - I will take care of the download module, just want to know this part.

**Comment by mleimeister** [comment]
Yes, this should do it. But you could also first download all the speakers you're interested in into one folder and then just grab all the wav files in there.

**Comment by harishyadav1465** [comment]
Hi, i am getting below error!


TypeError                                 Traceback (most recent call last)
<ipython-input-59-ac34ec498b69> in <module>()
     95     logits = tf.transpose(logits, (1, 0, 2))
     96 
---> 97     loss = ctc.ctc_loss(logits, targets, seq_len)
     98     cost = tf.reduce_mean(loss)
     99 

/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/ctc_ops.pyc in ctc_loss(labels, inputs, sequence_length, preprocess_collapse_repeated, ctc_merge_repeated, ignore_longer_outputs_than_inputs, time_major)
    137   # _CTCLossGrad() below.
    138   if not isinstance(labels, sparse_tensor.SparseTensor):
--> 139     raise TypeError("Expected labels (first argument) to be a SparseTensor")
    140 
    141   # For internal calculations, we transpose to [time, batch, num_classes]

TypeError: Expected labels (first argument) to be a SparseTensor
